# Dependencies
markdown:         kramdown
rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Füzi Péter
tagline:          'digital humanities'
description:      ''
url:              http://fzpeter/github.io
baseurl:          '/'
paginate:         5

analytics :
  provider : google
  google :
      tracking_id : 'UA-3302902-5'

author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

# Custom vars
#version:          1.0.0

github:
 # repo:           https://github.com/poole/lanyon
